# This is a basic workflow to help you get started with Actions

name: CI-I18N

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0-14,16-23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - run: 'echo "$SSH_KEY" > cicd_i18n && chmod 600 cicd_i18n'
      shell: bash
      env:
        SSH_KEY: ${{secrets.CICD_RELEASE}}

    - run: 'echo "$CROWDIN_YAML" > translations/crowdin.yaml && chmod 600 translations/crowdin.yaml'
      shell: bash
      env:
        CROWDIN_YAML: ${{secrets.CROWDIN_YAML}}

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        repository: jfesler/dummyvalue
        path: .
        push: false
